Tool/openproject-dev/modules/costs/config/routes.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

OpenProject::Application.routes.draw do
  scope 'projects/:project_id', as: 'projects' do
    resources :cost_entries, controller: 'costlog', only: %i[new create]

    resources :hourly_rates, only: %i[show edit update] do
      post :set_rate, on: :member
    end
  end

  scope 'projects/:project_id', as: 'project', module: 'projects' do
    namespace 'settings' do
      resource :time_entry_activities, only: %i[show update]
    end
  end

  scope 'work_packages/:work_package_id', as: 'work_packages' do
    resources :cost_entries, controller: 'costlog', only: %i[new]
  end

  resources :cost_entries, controller: 'costlog', only: %i[edit update destroy]

  resources :cost_types, only: %i[index new edit update create destroy] do
    member do
      # TODO: check if this can be replaced with update method
      put :set_rate
      patch :restore
    end
  end

  # TODO: this is a duplicate from a route defined under project/:project_id, check whether we really want to do that
  resources :hourly_rates, only: %i[edit update]
end

Tool/openproject-dev/modules/costs/app/models/hourly_rate.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class HourlyRate < Rate
  validates_uniqueness_of :valid_from, scope: %i[user_id project_id]
  validates_presence_of :user_id, :project_id, :valid_from
  validate :change_of_user_only_on_first_creation

  def previous(reference_date = valid_from)
    # This might return a default rate
    user.rate_at(reference_date - 1, project)
  end

  def next(reference_date = valid_from)
    HourlyRate
      .where(['user_id = ? and project_id = ? and valid_from > ?',
              user_id, project_id, reference_date])
      .order(Arel.sql('valid_from ASC'))
      .first
  end

  def self.history_for_user(usr)
    projects_with_costs = Project.has_module(:costs)
                                        .active
                                        .visible
                                        .order(:name)

    permitted_projects = Project.has_module(:costs)
                                .active
                                .allowed_to(User.current, :view_hourly_rates)

    rates_by_project = HourlyRate.where(user_id: usr, project_id: permitted_projects)
                                 .includes(:project)
                                 .order("#{HourlyRate.table_name}.valid_from desc")
                                 .group_by(&:project)

    rates = {}

    projects_with_costs.each do |project|
      rates[project] = rates_by_project.fetch(project, [])
    end

    # FIXME: What permissions to apply here?
    rates[nil] = DefaultHourlyRate
                   .where(user_id: usr)
                   .order("#{DefaultHourlyRate.table_name}.valid_from desc")

    rates
  end

  def self.at_date_for_user_in_project(date, user_id, project = nil, include_default = true)
    user_id = user_id.id if user_id.is_a?(User)

    unless project.nil?
      rate = where(['user_id = ? and project_id = ? and valid_from <= ?', user_id, project, date])
             .order(Arel.sql('valid_from DESC'))
             .first
      if rate.nil?
        project = Project.find(project) unless project.is_a?(Project)
        rate = where(['user_id = ? and project_id in (?) and valid_from <= ?',
                      user_id,
                      project.ancestors.to_a,
                      date])
               .includes(:project)
               .order(Arel.sql('projects.lft DESC, valid_from DESC'))
               .first
      end
    end
    rate ||= DefaultHourlyRate.at_for_user(date, user_id) if include_default
    rate
  end

  private

  def change_of_user_only_on_first_creation
    # Only allow change of project and user on first creation
    return if new_record?

    errors.add :project_id, :invalid if project_id_changed?
    errors.add :user_id, :invalid if user_id_changed?
  end
end

Tool/openproject-dev/modules/costs/app/controllers/hourly_rates_controller.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class HourlyRatesController < ApplicationController
  helper :users
  helper :sort
  include SortHelper
  helper :hourly_rates
  include HourlyRatesHelper

  before_action :find_user, only: %i[show edit update set_rate]

  before_action :find_optional_project, only: %i[show edit update]
  before_action :find_project, only: [:set_rate]

  # #show, #edit have their own authorization
  before_action :authorize, except: %i[show edit update]

  # TODO: this should be an index
  def show
    if @project
      return deny_access unless User.current.allowed_to?(:view_hourly_rates, @project, for: @user)

      @rates = HourlyRate.where(user_id: @user, project_id: @project)
               .order("#{HourlyRate.table_name}.valid_from desc")
    else
      @rates = HourlyRate.history_for_user(@user)
      @rates_default = @rates.delete(nil)
    end
  end

  def edit
    # TODO: split into edit and update
    # remove code where appropriate
    if @project
      # Hourly Rate
      return deny_access unless User.current.allowed_to?(:edit_hourly_rates, @project)
    else
      # Default Hourly Rate
      return deny_access unless User.current.admin?
    end

    if @project.nil?
      @rates = DefaultHourlyRate.where(user_id: @user)
               .order("#{DefaultHourlyRate.table_name}.valid_from desc")
               .to_a
      @rates << @user.default_rates.build(valid_from: Date.today) if @rates.empty?
    else
      @rates = @user.rates.select { |r| r.project_id == @project.id }.sort { |a, b| b.valid_from <=> a.valid_from }.to_a
      @rates << @user.rates.build(valid_from: Date.today, project: @project) if @rates.empty?
    end

    render action: 'edit', layout: !request.xhr?
  end

  current_menu_item :edit do
    :budgets
  end

  def update
    # TODO: copied over from edit
    # remove code where appropriate
    if @project
      # Hourly Rate
      return deny_access unless User.current.allowed_to?(:edit_hourly_rates, @project)
    else
      # Default Hourly Rate
      return deny_access unless User.current.admin?
    end

    if params.include? 'user'
      update_rates @user,
                   @project,
                   permitted_params.user_rates[:new_rate_attributes],
                   permitted_params.user_rates[:existing_rate_attributes]
    else
      delete_rates @user, @project
    end

    if @user.save
      flash[:notice] = t(:notice_successful_update)
      if @project.nil?
        redirect_back_or_default(controller: 'users', action: 'edit', id: @user)
      else
        redirect_back_or_default(action: 'show', id: @user, project_id: @project)
      end
    else
      if @project.nil?
        @rates = @user.default_rates
        @rates << @user.default_rates.build(valid_from: Date.today) if @rates.empty?
      else
        @rates = @user
                 .rates
                 .select { |r| r.project_id == @project.id }
                 .sort { |a, b| b.valid_from || Date.today <=> a.valid_from || Date.today }
        @rates << @user.rates.build(valid_from: Date.today, project: @project) if @rates.empty?
      end
      render action: 'edit', layout: !request.xhr?
    end
  end

  def set_rate
    today = Date.today

    rate = @user.rate_at(today, @project)
    rate = HourlyRate.new if rate.nil? || rate.valid_from != today

    rate.tap do |hr|
      hr.project    = @project
      hr.user       = @user
      hr.valid_from = today
      hr.rate = parse_number_string_to_number(params[:rate])
    end

    if rate.save
      if request.xhr?
        render :update do |page|
          page.replace_html "rate_for_#{@user.id}",
                            link_to(number_to_currency(rate.rate), action: 'edit', id: @user, project_id: @project)
        end
      else
        flash[:notice] = t(:notice_successful_update)
        redirect_to action: 'index'
      end
    end
  end

  private

  def update_rates(user, project, added_rates, changed_rates)
    user.add_rates(project, added_rates)
    user.set_existing_rates(project, changed_rates)
  end

  def delete_rates(user, project)
    if project.present?
      user.rates.delete_all
    else
      user.default_rates.delete_all
    end
  end

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_project
    @project = params[:project_id].blank? ? nil : Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_user
    @user = params[:id] ? User.find(params[:id]) : User.current
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

Tool/openproject-dev/modules/costs/app/helpers/hourly_rates_helper.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

module HourlyRatesHelper
  include CostlogHelper

  # Returns the rate that is the closest at the specified date and that is
  # defined in the specified projects or it's ancestors. The ancestor chain
  # is traversed from the specified project upwards.
  #
  # Expects all_rates to be all the rates that the user possibly has
  # grouped by project typically by having called HourlyRates.history_for_user
  #
  # This is faster than calling current_rate for each project
  def at_date_in_project_with_ancestors(at_date, all_rates, project)
    self_and_ancestors = all_rates.keys
                                  .select { |ancestor| ancestor.lft <= project.lft && ancestor.rgt >= project.rgt }
                                  .sort_by(&:lft)
                                  .reverse

    self_and_ancestors.each do |ancestor|
      rate = all_rates[ancestor].select { |rate| rate.valid_from <= at_date }
                                .max_by(&:valid_from)

      return rate if rate
    end

    nil
  end
end

Tool/openproject-dev/modules/costs/app/views/hourly_rates/_list.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<% @rates.each_pair do |project, rates| %>
  <%= render :partial => 'hourly_rates/list_project', :locals => { rates: rates, project: project, all_rates: @rates } %>
<% end %>

Tool/openproject-dev/modules/costs/app/views/hourly_rates/_list_default.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>
<div class="user-rate-history-list">
<div class="contextual">
  <%= link_to t(:button_update), edit_hourly_rate_path(@user), :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
</div>
<h3><%= User.human_attribute_name(:default_rates) %></h3>
<% if @rates_default.blank? %>
  <%= no_results_box %>
<% else %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table rates">
        <colgroup>
          <col opHighlightCol>
          <col opHighlightCol>
          <col opHighlightCol>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.human_attribute_name(:valid_from) %>
                  </span>
                </div>
              </div>
            </th>
            <th class="currency">
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= User.human_attribute_name(:current_rate) %>
                  </span>
                </div>
              </div>
            </th>
          </tr>
        </thead>
        <tbody id="rates_body">
        <% current_rate = @user.current_default_rate() %>
        <%- @rates_default.each do |rate| -%>
          <tr>
            <td style="padding-right: 1em;"><%= rate.valid_from %></td>
            <td class="currency"><%= number_to_currency(rate.rate) %></td>
            <td><%= rate == current_rate ? icon_wrapper('icon-context icon-checkmark',I18n.t(:general_text_Yes)) : "" %></td>
          </tr>
        <%- end -%>
        </tbody>
      </table>

    </div>
  </div>
<% end %>
</div>

Tool/openproject-dev/modules/costs/app/views/hourly_rates/_list_project.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<%
  rates = @rates unless rates
  project = @project unless project

  current_rate = if @all_rates
                   at_date_in_project_with_ancestors(Date.today, all_rates, project)
                 else
                   current_rate = @user.current_rate(project)
                 end
%>
<div class="user-rate-history-list">
<div class="contextual">
  <% if project && User.current.allowed_to?({:controller => '/hourly_rates', :action => 'edit'}, project) %>
    <%= link_to t(:button_update), {:controller => '/hourly_rates', :action => 'edit', :project_id => project, :id => @user}, :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
  <% end %>
</div>
<h3><%=h project.name %><%= (" - " + number_to_currency(current_rate.rate)) if current_rate %></h3>
<% if rates.empty? %>
  <%= no_results_box %>
<% else %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table rates">
        <colgroup>
          <col opHighlightCol>
          <col opHighlightCol>
          <col opHighlightCol>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.human_attribute_name(:valid_from) %>
                  </span>
                </div>
              </div>
            </th>
            <th class="currency">
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= User.human_attribute_name(:current_rate) %>
                  </span>
                </div>
              </div>
            </th>
          </tr>
        </thead>
        <tbody id="rates_body">
        <%- rates.each do |rate| -%>
          <tr>
            <td style="padding-right: 1em;"><%= rate.valid_from %></td>
            <td class="currency"><%= number_to_currency(rate.rate) %></td>
            <td><%= rate == current_rate ? icon_wrapper('icon-context icon-checkmark',I18n.t(:general_text_Yes)) : "" %></td>
          </tr>
        <%- end -%>
        </tbody>
      </table>

    </div>
  </div>
<% end %>
</div>

Tool/openproject-dev/modules/costs/app/views/hourly_rates/_rate.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<%-
  templated ||= false
  index ||= "INDEX"
  new_or_existing = rate.new_record? ? 'new' : 'existing'
  id_or_index = rate.new_record? ? index : rate.id
  prefix = "user[#{new_or_existing}_rate_attributes][]"
  id_prefix = "user_#{new_or_existing}_rate_attributes_#{id_or_index}"
  name_prefix = "user[#{new_or_existing}_rate_attributes][#{id_or_index}]"
  classes ||= ""
  classes += " subform-row-template" if templated
-%>

<%= fields_for prefix, rate do |rate_form| %>
  <tr class="subform-row <%= classes %>" id="<%= id_prefix %>">
    <td>
      <label class="hidden-for-sighted" for="<%= "#{id_prefix}_valid_from" %>"><%= Rate.human_attribute_name(:valid_from) %></label>
      <%= rate_form.text_field :valid_from,
                               class: 'date costs-date-picker -augmented-datepicker',
                               index: id_or_index,
                               required: true %>
    </td>
    <td class="currency">
      <span class="inline-label">
        <label class="hidden-for-sighted" for="<%= "#{id_prefix}_rate" %>"><%= Rate.model_name.human %></label>
        <%= rate_form.text_field :rate,
                                 index: id_or_index,
                                 value: rate.rate ? rate.rate.round(2) : "",
                                 required: true %>
        <span class="form-label">
          <%= Setting.plugin_costs['costs_currency'] %>
        </span>
      </span>
    </td>
    <td class="buttons">
      <a href="#" class="delete-row-button no-decoration-on-hover">
        <%= op_icon('icon-context icon-delete', title: t(:button_delete)) %>
      </a>
    </td>
  </tr>
<% end %>

Tool/openproject-dev/modules/costs/app/views/hourly_rates/edit.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<% html_title t(:label_administration), "#{t(:label_edit)} #{I18n.t((@project.nil? ? :caption_default_rate_history_for : :caption_rate_history_for), user: ' ')} #{@user.name}" %>

<%= toolbar title: (@project.nil? ? t(:caption_default_rate_history_for, user: @user.name) :  t(:caption_rate_history_for_project, user: @user.name, project: @project.name) ) %>

<%- default_rate = @user.current_default_rate -%>
<% if default_rate%>
<p><strong><%= t(:label_current_default_rate) %>:</strong> <%= number_to_currency(default_rate.rate)%></p>
<% end %>

<costs-subform item-count="<%= @rates.count %>">
<%= labelled_tabular_form_for @user, url: {action: 'update', project_id: @project}, method: :put do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= error_messages_for 'user' %>
  <%- @rates.each do |rate| -%>
    <%- @rate = rate -%>
    <%= error_messages_for 'rate' %>
  <%- end -%>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table rates" width="200px">
        <colgroup>
          <col opHighlightCol>
          <col opHighlightCol>
          <col>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.human_attribute_name(:valid_from) %>
                  </span>
                </div>
              </div>
            </th>
            <th class="currency">
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
        </thead>
        <tbody id="rates_body" class="subform-container">
          <%= render partial: "hourly_rates/rate", object: HourlyRate.new, locals: { templated: true } %>
          <%- @rates.each_with_index do |rate, index| -%>
            <%= render partial: 'rate', object: rate, locals: {index: index} %>
          <%- end -%>
        </tbody>
      </table>

    </div>
  </div>
  <div class="wp-inline-create-button">
    <a href="#" class="add-row-button wp-inline-create--add-link">
      <%= op_icon('icon icon-add') %>
        <%= t(:button_add_rate) %>
    </a>
  </div>
  <div class="generic-table--action-buttons">
    <%= styled_button_tag t(:button_save), class: '-with-icon icon-checkmark' %>
  </div>
<% end %>
</costs-subform>

Tool/openproject-dev/modules/costs/app/views/hourly_rates/show.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2021 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<% html_title t(:label_administration), t(:caption_rate_history_for, user: @user.name) %>

<%= toolbar title: t(:caption_rate_history_for, :user => @user.name) %>

<% if @project %>
  <% html_title t(:caption_rate_history_for, user: @user.name) %>

  <%= render :partial => 'list_project' %>
<% else %>
  <% html_title t(:label_administration), t(:caption_rate_history_for, user: @user.name) %>

  <%= render :partial => 'list_default' %>
  <%= render :partial => 'list' %>
<% end %>